name: routing_app
description: Hybrid Routing App (Google Map + HERE Routing REST v8 + TMS UI)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.2.0
  dio: ^5.4.0

  # Location
  geolocator: ^12.0.0

  # Google Map (Android)
  google_maps_flutter: ^2.7.0

  # Google Places Autocomplete
  google_places_flutter: ^2.0.8

  # Utils
  uuid: ^4.4.0
  collection: ^1.18.0

  # Environment variables (nếu sau này tách key)
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
